package com.itmuch.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-09-02T16:07:54.433+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://webservice.itmuch.com", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectById", targetNamespace = "http://webservice.itmuch.com", className = "com.itmuch.webservice.SelectById")
    @WebMethod
    @ResponseWrapper(localName = "selectByIdResponse", targetNamespace = "http://webservice.itmuch.com", className = "com.itmuch.webservice.SelectByIdResponse")
    public com.itmuch.webservice.UserResult selectById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateById", targetNamespace = "http://webservice.itmuch.com", className = "com.itmuch.webservice.UpdateById")
    @WebMethod
    @ResponseWrapper(localName = "updateByIdResponse", targetNamespace = "http://webservice.itmuch.com", className = "com.itmuch.webservice.UpdateByIdResponse")
    public com.itmuch.webservice.WSResult updateById(
        @WebParam(name = "user", targetNamespace = "")
        com.itmuch.webservice.WsEntitySoap user
    );
}
